//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAppToday
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ass_Prof_Classe
    {
        public int Id { get; set; }
        public int Prof_Id { get; set; }
        public string ClasseCode { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
